import type { CompElementInterface, ElementInterfaceIntersect, GlobalData, LottieLayer } from '@/types';
import type KeyframedValueProperty from '@/utils/properties/KeyframedValueProperty';
import SVGBaseElement from '@/elements/svg/SVGBaseElement';
export default class SVGCompElement extends SVGBaseElement {
    _debug?: boolean;
    addPendingElement: any;
    appendElementInPos: any;
    buildAllItems: any;
    buildElementParenting: any;
    buildItem: any;
    checkLayers: any;
    checkPendingElements: any;
    completeLayers: boolean;
    configAnimation: any;
    createAudio: any;
    createCamera: any;
    createFootage: any;
    createImage: any;
    createItem: any;
    createNull: any;
    createShape: any;
    createSolid: any;
    createText: any;
    currentFrame: number;
    destroy: any;
    destroyElements: any;
    elements: ElementInterfaceIntersect[];
    findIndexByInd: any;
    getElementById: any;
    getElementByPath: any;
    getElements: any;
    hide: any;
    includeLayers: any;
    initElement: any;
    initItems: any;
    layers?: LottieLayer[];
    pendingElements: ElementInterfaceIntersect[];
    prepareFrame: any;
    renderedFrame: number;
    renderFrame: any;
    renderInnerContent: any;
    searchExtraCompositions: any;
    setElements: any;
    setProjectInterface: any;
    setupGlobalData: any;
    show: any;
    supports3d: boolean;
    tm?: KeyframedValueProperty;
    updateContainerSize: any;
    constructor(data: LottieLayer, globalData: GlobalData, comp: CompElementInterface);
    createComp(data: LottieLayer): SVGCompElement;
}
