import { loadAnimation } from '@/animation/AnimationManager';
export declare const setSubframeRendering: (flag: boolean) => void;
declare const Lottie: {
    destroy: any;
    freeze: any;
    getRegisteredAnimations: any;
    goToAndStop: any;
    loadAnimation: any;
    mute: any;
    pause: any;
    play: any;
    registerAnimation: any;
    resize: any;
    setDirection: any;
    setLocationHref: any;
    setPrefix: any;
    setQuality: any;
    setSpeed: any;
    setSubframeRendering: (flag: boolean) => void;
    setVolume: any;
    stop: any;
    togglePause: any;
    unfreeze: any;
    unmute: any;
    useWebWorker: any;
    version: string;
};
export { loadAnimation };
export default Lottie;
