import { loadAnimation } from '@/animation/AnimationManager';
import Expressions from '@/utils/expressions/Expressions';
export declare const installPlugin: (type: string, plugin: typeof Expressions) => void, setSubframeRendering: (flag: boolean) => void;
declare const Lottie: {
    destroy: any;
    freeze: any;
    getRegisteredAnimations: any;
    goToAndStop: any;
    installPlugin: (type: string, plugin: typeof Expressions) => void;
    loadAnimation: any;
    mute: any;
    pause: any;
    play: any;
    registerAnimation: any;
    resize: any;
    setDirection: any;
    setLocationHref: any;
    setPrefix: any;
    setQuality: any;
    setSpeed: any;
    setSubframeRendering: (flag: boolean) => void;
    setVolume: any;
    stop: any;
    togglePause: any;
    unfreeze: any;
    unmute: any;
    useWebWorker: any;
    version: string;
};
export { loadAnimation };
export default Lottie;
export { type default as AnimationItem } from '@/animation/AnimationItem';
export type { AddAnimationParams, AnimationConfiguration, AnimationData, AnimationDirection, Vector2 as AnimationSegment, AnimationSettings, ConvertParams, LottieAnimation, LottieAsset, LottieManifest, Result, Vector2 } from '@/types';
