import type ShapeGroupData from '@/elements/helpers/shapes/ShapeGroupData';
import type MaskElement from '@/elements/MaskElement';
import type { CompElementInterface, GlobalData, LottieLayer, Shape } from '@/types';
import type CompExpressionInterface from '@/utils/expressions/CompInterface';
import type LayerExpressionInterface from '@/utils/expressions/LayerInterface';
import type DynamicPropertyContainer from '@/utils/helpers/DynamicPropertyContainer';
import EffectsManager from '@/effects/EffectsManager';
export default abstract class BaseElement {
    baseElement?: HTMLElement | SVGGElement;
    comp?: CompElementInterface;
    compInterface?: CompExpressionInterface;
    data?: LottieLayer;
    dynamicProperties: DynamicPropertyContainer[];
    effectsManager?: EffectsManager;
    frameDuration: number;
    globalData?: GlobalData;
    itemsData: ShapeGroupData[];
    layerElement?: SVGGElement | HTMLElement;
    layerId?: string;
    layerInterface?: null | LayerExpressionInterface;
    maskManager?: MaskElement;
    shapesData: Shape[];
    type?: unknown;
    buildAllItems(): void;
    checkLayers(_frame?: number): void;
    checkMasks(): boolean;
    destroy(): void;
    destroyBaseElement(): void;
    getBaseElement(): SVGElement | HTMLElement | null;
    getType(): unknown;
    initBaseData(data: LottieLayer, globalData: GlobalData, comp: CompElementInterface): void;
    initExpressions(): void;
    setBlendMode(): void;
    sourceRectAtTime(): void;
}
