import type { CompElementInterface, ElementInterfaceIntersect, GlobalData, LottieLayer } from '../../types';
import CompElement from '../../elements/CompElement';
export default class CVCompElement extends CompElement {
    buildElementParenting: (element: ElementInterfaceIntersect, parentName?: number, hierarchy?: ElementInterfaceIntersect[]) => void;
    buildItem: (pos: number) => void;
    canvasContext?: CanvasRenderingContext2D;
    checkPendingElements: () => void;
    clearCanvas: (canvasContext?: CanvasRenderingContext2D | OffscreenCanvasRenderingContext2D | null) => void;
    configAnimation: (animData: import("../../types").AnimationData) => void;
    createContainerElements: () => void;
    createContent: () => void;
    createElements: () => void;
    createImage: (data: LottieLayer) => import("./CVImageElement").default;
    createRenderableComponents: () => void;
    createShape: (data: LottieLayer) => import("./CVShapeElement").default;
    createSolid: (data: LottieLayer) => import("./CVSolidElement").default;
    createText: (data: LottieLayer) => import("./CVTextElement").default;
    ctxFill: (rule?: CanvasFillRule) => void;
    ctxFillRect: (x: number, y: number, w: number, h: number) => void;
    ctxFillStyle: (value?: string) => void;
    ctxLineCap: (value: CanvasLineCap) => void;
    ctxLineJoin: (value: CanvasLineJoin) => void;
    ctxLineWidth: (value: number) => void;
    ctxMiterLimit: (value: number) => void;
    ctxOpacity: (op?: number) => void;
    ctxStroke: () => void;
    ctxStrokeStyle: (value?: string) => void;
    ctxTransform: (props: Float32Array) => void;
    exitLayer: () => void;
    hide: () => void;
    hideElement: () => void;
    initRendererElement: () => void;
    pendingElements: ElementInterfaceIntersect[];
    prepareLayer: () => void;
    renderFrame: (forceRender?: boolean) => void;
    reset: () => void;
    restore: (actionFlag?: boolean) => void;
    save: (_flag?: boolean) => void;
    setBlendMode: () => void;
    show: () => void;
    showElement: () => void;
    updateContainerSize: (width?: number, height?: number) => void;
    constructor(data: LottieLayer, globalData: GlobalData, comp: CompElementInterface);
    createComp(data: LottieLayer): CVCompElement;
    destroy(): void;
    renderInnerContent(): void;
}
