import type { SVGStyleData } from '../../../elements/helpers/shapes/SVGStyleData';
import type { ElementInterfaceIntersect, Shape, ShapeDataInterface, SVGElementInterface, Transformer } from '../../../types';
import type { KeyframedValueProperty } from '../../../utils/properties/KeyframedValueProperty';
import type { MultiDimensionalProperty } from '../../../utils/properties/MultiDimensionalProperty';
import type { ValueProperty } from '../../../utils/properties/ValueProperty';
import { DynamicPropertyContainer } from '../../../utils/helpers/DynamicPropertyContainer';
import { GradientProperty } from '../../../utils/shapes/properties/GradientProperty';
export declare class SVGGradientFillStyleData extends DynamicPropertyContainer {
    a?: undefined | ValueProperty;
    cst: SVGStopElement[];
    e?: undefined | MultiDimensionalProperty;
    g?: undefined | GradientProperty;
    gf?: undefined | SVGGradientElement;
    gr?: undefined | SVGGElement;
    h?: undefined | KeyframedValueProperty;
    it: ShapeDataInterface[];
    maskId?: undefined | string;
    ms?: undefined | SVGMaskElement;
    o?: undefined | ValueProperty;
    of?: undefined | SVGElement;
    ost: SVGStopElement[];
    prevViewData: SVGElementInterface[];
    s?: undefined | MultiDimensionalProperty;
    stops: SVGStopElement[];
    style?: undefined | SVGStyleData;
    transform?: undefined | Transformer;
    constructor(elem: ElementInterfaceIntersect, data: Shape, styleData: SVGStyleData);
    initGradientData(elem: ElementInterfaceIntersect, data: Shape, styleData: SVGStyleData): void;
    setGradientData(pathElement: SVGElement, data: Shape): void;
    setGradientOpacity(data: Shape, styleData: SVGStyleData): void;
}
