import type { ExpressionInterface, ExpressionInterfaces, GetInterface } from '../types';
import type Expressions from '../utils/expressions/Expressions';
export declare const initialDefaultFrame = -999999, roundCorner = 0.5519;
export declare const setExpressionsPlugin: (value: typeof Expressions) => void, getExpressionsPlugin: () => typeof Expressions | null, setExpressionInterfaces: (getInterface: (type: keyof ExpressionInterfaces) => ExpressionInterface) => void, getExpressionInterfaces: () => GetInterface | null;
export declare const setDefaultCurveSegments: (value: number) => void, getDefaultCurveSegments: () => number;
export declare const setWebWorker: (flag: boolean) => void, getWebWorker: () => boolean;
export declare const setSubframeEnabled: (flag: boolean) => void, getSubframeEnabled: () => boolean;
export declare const setLocationHref: (value: string) => void, getLocationHref: () => string;
export declare const setIDPrefix: (value: string) => void, getIDPrefix: () => string;
export declare const getShouldRoundValues: () => boolean, setShouldRoundValues: (value: boolean) => void, setQuality: (value: string | number) => void;
