import type { AnimationConfiguration, AnimationData, AnimationDirection } from '../types';
import AnimationItem from '../animation/AnimationItem';
import { RendererType } from '../utils/enums';
export declare function destroy(animation?: string): void;
export declare function freeze(): void;
export declare function getRegisteredAnimations(): (AnimationItem | undefined)[];
export declare function goToAndStop(value: number, isFrame?: boolean, animation?: string): void;
export declare function loadAnimation(params: AnimationConfiguration): AnimationItem;
export declare function mute(animation?: string): void;
export declare function pause(animation?: string): void;
export declare function play(animation?: string): void;
export declare function registerAnimation(element: HTMLElement | null, animationData?: AnimationData): AnimationItem | null | undefined;
export declare function resize(): void;
export declare function searchAnimations(animationData?: AnimationData, standalone?: boolean, rendererFromProps?: RendererType): void;
export declare function setDirection(val: AnimationDirection, animation?: string): void;
export declare function setSpeed(val: number, animation?: string): void;
export declare function setVolume(val: number, animation?: string): void;
export declare function stop(animation?: string): void;
export declare function togglePause(animation?: string): void;
export declare function unfreeze(): void;
export declare function unmute(animation?: string): void;
declare const AnimationManager: {
    destroy: typeof destroy;
    freeze: typeof freeze;
    getRegisteredAnimations: typeof getRegisteredAnimations;
    goToAndStop: typeof goToAndStop;
    loadAnimation: typeof loadAnimation;
    mute: typeof mute;
    pause: typeof pause;
    play: typeof play;
    registerAnimation: typeof registerAnimation;
    resize: typeof resize;
    searchAnimations: typeof searchAnimations;
    setDirection: typeof setDirection;
    setSpeed: typeof setSpeed;
    setVolume: typeof setVolume;
    stop: typeof stop;
    togglePause: typeof togglePause;
    unfreeze: typeof unfreeze;
    unmute: typeof unmute;
};
export default AnimationManager;
